runtime: python37

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto
  secure: always

env_variables:
  CLOUD_SQL_CONNECTION_NAME: yarin-nes-sales:europe-west1:nes-data
  CLOUD_SQL_USERNAME: root
